import connectMongo from "@/utlis/connectMongo";
import EnquiryModel from "@/models/enquiryModel";
import { NextResponse } from "next/server";

export async function POST(req) {
  try {
    const {
      title,
      description,
      image,
      created_at,
      description1,
      description2,
      description3,
      description4,
      description5,
      description6,
      description7,
      description8,
      description9,
      description10,
      description11,
      description12,
      description13,
      description14,
      description15,
      description16,
      image1,
      image2,
      image3,
      image4,
      image5,
      image6,
      image7,
      title1,
      title2,
      title3,
      title4,
      title5,
      title6,
      title7,
      title8,
      title9,
      title10,
      title11,
      title12,
      title13,
      title14,
      title15,
      title16,
    } = await req.json();
    const enquiry = {
      title,
      description,
      image,
      created_at,
      description1,
      description2,
      description3,
      description4,
      description5,
      description6,
      description7,
      description8,
      description9,
      description10,
      description11,
      description12,
      description13,
      description14,
      description15,
      description16,
      image1,
      image2,
      image3,
      image4,
      image5,
      image6,
      image7,
      title1,
      title2,
      title3,
      title4,
      title5,
      title6,
      title7,
      title8,
      title9,
      title10,
      title11,
      title12,
      title13,
      title14,
      title15,
      title16,
    };
    await connectMongo();
    await EnquiryModel.create(enquiry);
    return NextResponse.json({ message: "Post Uploaded " });
  } catch (error) {
    return NextResponse.json({ message: error._message });
  }
}
